version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

  telegram:
    build: ../telegram
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/static/media/

  backend:
    build: ../backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/static/media/

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - telegram

volumes:
  db_data:
  static_value:
  media_value:
